root CA AND/OR sni verify and macro fix
private-octopus/picoquic pull request #1180
Opened 2021-03-22 23:20 UTC by victorstewart

the comment says the openssl certificate verifier crashes if no name is specified but... that's not true the verifications are independent? 

certificate against roots happens in `X509_verify_cert` at [https://github.com/h2o/picotls/blob/c91baf9c9971332d9280a7062943c54a4f13a7ec/lib/openssl.c#L1235](https://github.com/h2o/picotls/blob/c91baf9c9971332d9280a7062943c54a4f13a7ec/lib/openssl.c#L1235)

and SNI against certificate common name or subject alt names happens in `X509_check_host` at [https://github.com/h2o/picotls/blob/c91baf9c9971332d9280a7062943c54a4f13a7ec/lib/openssl.c#L1270](https://github.com/h2o/picotls/blob/c91baf9c9971332d9280a7062943c54a4f13a7ec/lib/openssl.c#L1270)

2021-03-22 23:41 UTC, victorstewart commented
this is failing because it's not reading from the master of picotls. what's to be done?

2021-03-23 00:59 UTC, huitema requested changes
It looks good, but you have to update the picotls commit id in `./ci/build_picotls.sh` and `./ci/build_picotls.ps1`

2021-03-23 00:59 UTC, huitema commented on picoquic/tls_api.c
Don't you love Kazuho's macros? The callback structure `ptls_verify_certificate_t` is defined as 
```
PTLS_CALLBACK_TYPE(int, verify_certificate, ptls_t *tls,
                   int (**verify_sign)(void *verify_ctx, ptls_iovec_t data, ptls_iovec_t sign), void **verify_data,
                   ptls_iovec_t *certs, size_t num_certs);
```
in `picotls.h`. I assume that you changed that, I saw that Kazuho merged your changes. But then, your code depends from this latest commit in the `picotls` repo.

The `picoquic` builds call the scripts `./ci/build_picotls.sh` (for Unix) and `./ci/build_picotls.ps1` (for Windows), which contain code like:
```
# Build at a known-good commit
COMMIT_ID=d5e32519516e13520ddeffa85da97d2398197df2
```
You want to update that to a `picotls` commit number posterior to your changes, that should clear the failures of the check-in tests.

2021-03-23 03:35 UTC, huitema commented on picoquic/tls_api.c
Specifically, in file `(repo)/ci/build_picotls.h`, replace:
```
# Build at a known-good commit
COMMIT_ID=d5e32519516e13520ddeffa85da97d2398197df2
```
By:
```
# Build at a known-good commit
COMMIT_ID=c91baf9c9971332d9280a7062943c54a4f13a7ec
```
And in file `(repo)/ci/build_picotls.ps1`, replace:
```
# Build at a known-good commit
$COMMIT_ID="d5e32519516e13520ddeffa85da97d2398197df2"
```
by:
```
# Build at a known-good commit
$COMMIT_ID="c91baf9c9971332d9280a7062943c54a4f13a7ec"
```

2021-03-23 17:02 UTC, victorstewart commented
weird its now saying the test failed but... lol?

```
Tried 30 tests, 0 fails.
Error: Process completed with exit code 1.
```

2021-03-23 19:20 UTC, huitema commented
The "leaks" test verifies presence r absence of leks in two programs: picoquic_ct and picohttp_ct. In your case, the 30 picohttp tests pass, but there is a leak detected in one of the picoquic tests

2021-04-04 20:33 UTC, closed without merging